version: "3.7"

services:
  peer0:
    build: .
    image: phifd:latest
    hostname: peer0
    environment: 
      PHI_ME: peer0:peer0:9000
      PHI_REST: 0.0.0.0:8000
    ports:
      - "9000:9000"
      - "8000:8000"

  peer1:
    build: .
    image: phifd:latest
    hostname: peer1
    environment: 
      PHI_ME: peer1:peer1:9001
      PHI_REST: 0.0.0.0:8001
    ports:
      - "9001:9001"
      - "8001:8001"
  